[package]
name = "ipset_listener"
version = "0.1.0"
authors = ["Anthony Ruhier <anthony.ruhier@gmail.com>"]

[dependencies]
config = "0.1.3"
env_logger = "0.3"
lazy_static = "0.1.16"
log = "0.3.5"
regex = "0.1"
rustc-serialize = "0.3"
