[package]
name = "ipset_listener"
version = "0.1.0"
authors = ["Anthony Ruhier <anthony.ruhier@gmail.com>"]

[dependencies]
config = "0.5"
env_logger = "0.4"
lazy_static = "0.2"
log = "0.3"
regex = "0.2"
